name: automatize test python
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v4
      - name: Set up python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: 3.10
      - name: installing dependecy
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: executing testing
        run: |
          pytest -vv